name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33ee6b10d7ee539d9622b6e15e36e7010fa60f9eecc9ef295467d7e24d16e1ac"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
