name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.13"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df1ad51df97627b0b1a8cc3e283fbfa09c1cd93c6ac26cad36d7220263fa544d"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
