name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "534fb1e535ec52f319fed3a006757ac81ea0f86dd6a83d307a8b4631de7079f2"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
