name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "724ead6cb5f3317d6dbb3b2d1aebff137a6051ef0073c2fbf3ea522c57d3cab4"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
