name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.18"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d6584053ea259cef25ef0ee6b2015a1cd926e7b79ab3e1fe67a6963009ea831"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
