name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38b9eb37868529cc9a6b95b2d3ef490c1699142603309a0c339c129aee4a1201"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
