name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b62d3f9daa601ccc54731cfe5f523deab99125fa010595ba19804ca0efdeadc8"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
