name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "177c4257ab8d85082f94e2e37c623e6b3400023f3af164e1c59214f44e2bc78c"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
