name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.11"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77992aa14e3f74c5aa009d28005ecea95d71b876545b8bdf71ead36d62d2c5a2"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
