name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.10"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "607eaa0fd8cad89ffccf3b5a5960c5462c11bd3f5a1427161d30ce20af2b60fe"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
