name = "TTT Creative"
author = "The Tiny Taters"
version = "2.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b4703aa192649a22f9e64c22f28a6542c170eee141728f1f74f40ebeb398bce"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
