name = "TTT Creative"
author = "The Tiny Taters"
version = "1.1.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e9875156a388cd50b180863a1aedee656108091721f8f9ab24fd294064465cf"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
