name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ec9d372d87a80707abb7f6c5f3e44ceffec244b0bebc13f388d8f8824726da6"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
