name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76391f37824e5150f7d396fbca8ca802380f2303d83ff4641cd542adc4a70a24"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
