name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f9f14ad5895128d868fb0c667c2e7f13a0a804f9007f1d781d945846f590799"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
