name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ec52a7850f3c048bde7d6e8d772fbed6fa08d025b218728abc0a40109cd9f20"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
