name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9f2f04d2e6b3214901a3d9ecdd45166db3c53657b6e10942afd3a1acddec42d"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
