name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95bdee2d549e4f5cd6a22c8d45c7bdb4de95c1c6fd0ddb3d11d5336bf466c6cd"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
