name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.14"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d21787b2a6e11e6046b15cd155e25d04b4a92c12759a2af5ba2c0abcd380753"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
