name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d62326660029b8b502fbe0a64111eee47d5cab532fd3485f0fe6bcca46d8999"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
