name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bcb83f82ce108a66f31e782fad930963051609aef9024502177569f786ffe10"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
