name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ed707e78d0c0e1c458d8419bee06aa1eff20c06080dafaae124b3554f8bfcee"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
