name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99a0c59f2a65e7b0a281bbae614a5df8c3d7a834a37512c43fb1b39596031a17"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
