name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "041b1cc51590062e4084dc18ac1e890b157e49eb1dea5bd5fa1ab708d6ba44e7"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
