name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7dc8f187750dc544c1b97eab2fce5733ad12e1af2a7fcf9c7e64e5eec29e5ca7"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
