name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f24fc29d09bb557f1e372e953ae334500fc5bbf8984dbc312f8ae0ae969038"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
