name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.6"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5a3840559c589d6e819551f9c865fb36b3b5b7499bf4fc09f5535598a92f565"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
