name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bd5904e4f3560a37456c86209fdf1b7aa1c899cdda56f7c14b7668135511c9c"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
