name = "TTT Creative"
author = "The Tiny Taters"
version = "2.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6cf58ec556024d6cc239df13a2fd4440b4f31f0d958ce6830a0549c92b1f150"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
