name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "311c609adefef17fd0062f8cdfc2609105ab6cc3f641e08fcdf3c9425dbc2ce9"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
