name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7fe04917aae2a81d42055b46439d630d305d6e1089d3be503b51c36dec8b764"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
