name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.9"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a863c9ebcf8da019f4207c76b7ba0fe2ad8d6d839a6bbdcb5a412ddd6520fc16"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
