name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a05c4da3d54a051beda0ba86362d98016710dae0dc8582105a628ddad5c9acd8"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
