name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d089a3681fbe41646c5fc0eadd92c086cc7b6c772b892619778f18bdd5caf528"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
