name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dad0fbca46c65678ac17cfe3dea28123f1bc3aec5131eb43dc628550ee0ccc84"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
