name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.9"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a788225fc00d74a660f0e6f716e78f30e90b0d3b3aa8fff8a5a685f74e8c5bcd"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
