name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e09c6c2370cbee74d0eb0448d437f73d7346b3ec53f2f6c248d13063735ee61c"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
