name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.16"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63e6d2eb373e026d0da7d220dc638401d45a3dcaebd12df08c8dc26e4e45b279"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
