name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91367f64561366a332491c810ee21c581b4eb10764bc41dc66cca72b68e027dd"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
