name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.12"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ec997dd0df0bf4624ebdaf4e37926543c96542371917bf7a3d0bb6354510198"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
