name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.12"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82a06c6ea4d676596884f1daab47ffe753403efc5fdb5df4a197e238af7e5620"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
