name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.5"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1619db75d07b00fb66dd329f6966cf83559b9e91e6f228cfd0541d10e0375d0"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
