name = "TTT Creative"
author = "The Tiny Taters"
version = "2.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5434480e72f6c09bc9dae3c1102a4418c66b3a2e1c41d08a51bb9200813af5d"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
