name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.17"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1315b986a38aa51eaf46e13402ba37987a8e0cc4d75940eb2247feb04f5948a"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
