name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebe7d5094ae946f17417f6fdc5c3db31b1a562ccd526a313711c05ad6d5d3c50"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
