name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.8"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64c622a2d1be5e19ef351c774e903703f8449f1063ffd9d9bc47decd73f7dab1"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
