name = "TTT Creative"
author = "The Tiny Taters"
version = "2.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "704a48c9d813b51d4a6fcb2da6fb1550eda20c65003d6815576f130932324fa9"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
