name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e32f082ba1563ffea6e082ca2d4d32afe0253eb87b760fdfd24b707f7822febf"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
