name = "TTT Creative"
author = "The Tiny Taters"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "311ae941f29d09cb648285ba447bfb5c05d58871d0a48415acdfebb5fa87e0f4"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
