name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b712e083c68a33398fe7f82eab9ae8de93f7101e7e0b31270bb102df83c5f9"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
