name = "TTT Creative"
author = "The Tiny Taters"
version = "1.2.15"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a51c1dd3ccbb1ed7efc56d89a8c52f7d3e7537fb8fb76416652821d3625f921c"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
