name = "Better Op"
filename = "better-op-1.0.2.jar"
side = "server"

[download]
url = "https://github.com/The-Tiny-Taters/Better-Op/releases/download/v1.0.2/better-op-1.0.2.jar"
hash-format = "sha256"
hash = "14c8623dab3c28cea4220086bb4014edea05cea0ee7a6d61f4380ff76dffb495"
