name = "FabricHomes"
filename = "FabricHomes-0.1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3187/896/FabricHomes-0.1.2.jar"
hash-format = "murmur2"
hash = "2438161831"

[update]
[update.curseforge]
file-id = 3187896
project-id = 441291
release-channel = "beta"
