name = ":fritater:"
filename = "fritater-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/X0CU9Sb7/versions/1.0.0/fritater-1.0.0.jar"
hash-format = "sha512"
hash = "3ccbfa94ceeabd9b99478062f06ed861b2890aac7046c3e5eab7485e5120d13bd6268d6ee0e12aa61c8e92e68c9dbf065e638de99eff708f8f4a4268f709e14b"

[update]
[update.modrinth]
mod-id = "X0CU9Sb7"
version = "Vtxy4VKZ"
