name = ":fritater:"
filename = "fritater-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/X0CU9Sb7/versions/1.0.1/fritater-1.0.0.jar"
hash-format = "sha512"
hash = "b48905fdb2696cb383610b8fded92f1dc47d7378eb4e7f7f086a5ca9ade916cc8c1cf6b0465afc425709ac323a4554bc7cbe55453f1d7cd52321dc9d65eb2903"

[update]
[update.modrinth]
mod-id = "X0CU9Sb7"
version = "dUY3zwk1"
