name = "Not Enough Crashes (Fabric)"
filename = "notenoughcrashes-3.1.7-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3215/751/notenoughcrashes-3.1.7-fabric.jar"
hash-format = "murmur2"
hash = "2814868899"

[update]
[update.curseforge]
file-id = 3215751
project-id = 353890
release-channel = "beta"
