name = "Rat's Mischief"
filename = "ratsmischief-1.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3223/139/ratsmischief-1.0.2.jar"
hash-format = "murmur2"
hash = "3988093374"

[update]
[update.curseforge]
file-id = 3223139
project-id = 431787
release-channel = "beta"
