name = "Through the looking glass"
filename = "TTLG-ALPHA.12.jar"
side = "both"

[download]
url = "https://github.com/Dragonoidzero/Through-the-Looking-Glass/releases/download/2.0.0-alpha.12/TTLG-ALPHA.12.jar"
hash-format = "sha256"
hash = "35cdbdb0b997b2b672c5f99ec49fa1d4b93fa9beeafa1438be95a9671213c5d1"
