name = "TomsServerUtils"
filename = "TomsServerTools-v0.4.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/ul4zTWk4/versions/0.4.0/TomsServerTools-0.4.0.jar"
hash-format = "sha256"
hash = "FDC95AFA74D560867565A97AD7A2F24F28BC5CCC4D5AE80DC52708983E9CFB1E"

