name = "TomsServerUtils"
filename = "TomsServerTools-v0.6.0.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/ul4zTWk4/versions/0.6.0/TomsServerTools-0.6.0.jar"
hash-format = "sha512"
hash = "d0fe38f0502c1f0f68f64aa165f1dbe181846de0fd955f91004831d0015202933b1b3e13b55e9cc61c17c4e15434b651febe079a379518cb77d76f24f8eb38dc"

[update]
[update.modrinth]
mod-id = "ul4zTWk4"
version = "OE2m3ij5"
