name = "UnderFabric"
filename = "underfabric-1.0.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/UXm0RHnT/versions/1.0.0/underfabric-1.0.0.jar"
hash-format = "sha512"
hash = "TODO"

[update]
[update.modrinth]
mod-id = "UXm0RHnT"
version = "Df0TSN6O"