name = "UnderFabric"
filename = "underfabric-1.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/UXm0RHnT/versions/1.1.0/underfabric-1.1.0.jar"
hash-format = "sha512"
hash = "6095bbd848e5c1329c9447899db9bfa690ea8572654d0f21edaced5cfb9b8a3fe8a069e5930a366c6bf89da6ff831910cfd5c87670db87a6eb3e20007424a297"

[update]
[update.modrinth]
mod-id = "UXm0RHnT"
version = "tYCzUAmk"
